// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Goga211/go-auth/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockAppProvider is an autogenerated mock type for the AppProvider type
type MockAppProvider struct {
	mock.Mock
}

type MockAppProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppProvider) EXPECT() *MockAppProvider_Expecter {
	return &MockAppProvider_Expecter{mock: &_m.Mock}
}

// App provides a mock function with given fields: ctx, appID
func (_m *MockAppProvider) App(ctx context.Context, appID int) (model.App, error) {
	ret := _m.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for App")
	}

	var r0 model.App
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (model.App, error)); ok {
		return rf(ctx, appID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) model.App); ok {
		r0 = rf(ctx, appID)
	} else {
		r0 = ret.Get(0).(model.App)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, appID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAppProvider_App_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'App'
type MockAppProvider_App_Call struct {
	*mock.Call
}

// App is a helper method to define mock.On call
//   - ctx context.Context
//   - appID int
func (_e *MockAppProvider_Expecter) App(ctx interface{}, appID interface{}) *MockAppProvider_App_Call {
	return &MockAppProvider_App_Call{Call: _e.mock.On("App", ctx, appID)}
}

func (_c *MockAppProvider_App_Call) Run(run func(ctx context.Context, appID int)) *MockAppProvider_App_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAppProvider_App_Call) Return(_a0 model.App, _a1 error) *MockAppProvider_App_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAppProvider_App_Call) RunAndReturn(run func(context.Context, int) (model.App, error)) *MockAppProvider_App_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAppProvider creates a new instance of MockAppProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppProvider {
	mock := &MockAppProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
