// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserSaver is an autogenerated mock type for the UserSaver type
type MockUserSaver struct {
	mock.Mock
}

type MockUserSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSaver) EXPECT() *MockUserSaver_Expecter {
	return &MockUserSaver_Expecter{mock: &_m.Mock}
}

// SaveUser provides a mock function with given fields: ctx, email, passHash
func (_m *MockUserSaver) SaveUser(ctx context.Context, email string, passHash []byte) (int64, error) {
	ret := _m.Called(ctx, email, passHash)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (int64, error)); ok {
		return rf(ctx, email, passHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) int64); ok {
		r0 = rf(ctx, email, passHash)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, email, passHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserSaver_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserSaver_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passHash []byte
func (_e *MockUserSaver_Expecter) SaveUser(ctx interface{}, email interface{}, passHash interface{}) *MockUserSaver_SaveUser_Call {
	return &MockUserSaver_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, email, passHash)}
}

func (_c *MockUserSaver_SaveUser_Call) Run(run func(ctx context.Context, email string, passHash []byte)) *MockUserSaver_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockUserSaver_SaveUser_Call) Return(uid int64, err error) *MockUserSaver_SaveUser_Call {
	_c.Call.Return(uid, err)
	return _c
}

func (_c *MockUserSaver_SaveUser_Call) RunAndReturn(run func(context.Context, string, []byte) (int64, error)) *MockUserSaver_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserSaver creates a new instance of MockUserSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSaver {
	mock := &MockUserSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
